### ISSUE TITLE
Preview on Circle.cl needs relative paths for style

### ISSUE THREAD

**Issue by vsoch** [vsoch/nipy-jekyll#4]

**Comment by bcipolli** [comment]
Most discussion happened in the mailing list, here:
https://mail.python.org/pipermail/neuroimaging/2015-August/000307.html

. Seems we've identified this issue and are working towards solving it, so better to come here? @arokem and @matthew-brett were participants, so I'm looping them in.

Looks like the current solution is simply to configure the baseurl properly for each publishing platform. I'm amazed that this is so hard.

@vsoch , you mentioned an issue about how blog posts render. If you'd like help solving it, could you give a bit of detail here? I can't understand why it wouldn't be solved by setting up the config properly, and want to make sure we're following a nice, clean Jekyll workflow (which was kind of a requirement for choosing Jekyll along the way)

**Comment by vsoch** [comment]
The bug is that site.baseurl is not defined on the index.html page:

https://circle-artifacts.com/gh/vsoch/nipy-jekyll/61/artifacts/0/home/ubuntu/nipy-jekyll/_site/index.html

The h2 tag where I defined it is empty.

**Comment by bcipolli** [comment]
I believe the issue is that the URLs aren't using the baseurl properly. I
saw this too.

The baseurl should NOT have a trailing slash. and every URL that prepends
baseurl should be an absolute URL: /css/bootstrap.css.

Relative URLs should start without a slash, and should not prepend baseurl.

The css / js urls there should be the former, not the latter.

**Comment by bcipolli** [comment]
@vsoch if you have a branch, I can just make the fix--I did it locally when I was playing around.

**Comment by vsoch** [comment]
Use the ben branch:

https://github.com/vsoch/nipy-jekyll/tree/ben

Looks like I gave the global config my wrong email so it's referencing my secret account, manbat, heh.

**Comment by vsoch** [comment]
I think we've fixed this one, so I'm closing!
